#[derive(Debug, Clone)]
pub struct Theme {
    pub bg: &'static str,
    pub surface: &'static str,
    pub border: &'static str,
    pub fg: &'static str,
    pub accent: &'static str,
    pub warning: &'static str,
    pub error: &'static str,
    pub muted: &'static str,
    pub keyword: &'static str,
    pub typ: &'static str,
    pub string: &'static str,
    pub function: &'static str,
    pub number: &'static str,
    pub comment: &'static str,
    pub operator: &'static str,
}

pub const VESPER: Theme = Theme {
    bg: "#141414",
    surface: "#1c1c1c",
    border: "#3c3c41",
    fg: "#e1e1e1",
    accent: "#bb9af7",
    warning: "#e0af68",
    error: "#f7768e",
    muted: "#6c6c6c",
    keyword: "#bb9af7",
    typ: "#7aa2f7",
    string: "#9ece6a",
    function: "#7aa2f7",
    number: "#ff9e64",
    comment: "#6c6c6c",
    operator: "#89ddff",
};
