#[derive(Debug, Clone)]
pub struct Theme {
    pub bg: &'static str,
    pub surface: &'static str,
    pub border: &'static str,
    pub fg: &'static str,
    pub accent: &'static str,
    pub warning: &'static str,
    pub error: &'static str,
    pub muted: &'static str,
    pub keyword: &'static str,
    pub typ: &'static str,
    pub string: &'static str,
    pub function: &'static str,
    pub number: &'static str,
    pub comment: &'static str,
    pub operator: &'static str,
    pub placeholder: &'static str,
    pub selected: &'static str,
}

pub const VESPER: Theme = Theme {
    bg: "#101010",
    surface: "#1c1c1c",
    border: "#343434",
    fg: "#ffffff",
    accent: "#ffc799",
    warning: "#ffc799",
    error: "#ff8080",
    muted: "#a0a0a0",
    keyword: "#a0a0a0",
    typ: "#ffc799",
    string: "#99ffe4",
    function: "#ffc799",
    number: "#ffc799",
    comment: "#8b8b8b",
    operator: "#a0a0a0",
    placeholder: "#7e7e7e",
    selected: "#232323",
};
